# <center>  <div style="background-color:#9E1A1A;color:white;padding:5%"> <font size="6"> Mini-projet 1 : L'IA pour les mesures des champs électromagnétiques <br> <br> <br>  <center> Hazem Aich  <font size="4"> <br> 2 DNI 1 </center> </div>

#   ` Test du modèle avec des  données originales`

In [4]:
%matplotlib inline
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('ANFR_Herault_Mesures_originales_pour_jpynb1.csv',delimiter=';')
df.head()

,Numéro de mesure,Longitude,Latitude,Position,Insee,Adresse,Complément,Code postal,Commune,Date de mesure,Mesure réalisée,Rapport,Conformité de la mesure,Niveau global,Type d'environnement,Laboratoire
0,175,3.91611,43.58528,"03° 54' 58.00'' Est, 43° 35' 07.00'' Nord",34129,Mas de Gau,NaN,34970,LATTES,06/12/2001,En extérieur,FicheMesure175.pdf,Oui,0.00,Divers,SATELIT
1,180,4.04194,43.64694,"04° 02' 31.00'' Est, 43° 38' 49.00'' Nord",34176,5539 Rue Lou Claou de la Oulivettas,NaN,34130,MUDAISON,06/12/2001,En extérieur,FicheMesure180.pdf,Oui,0.00,Divers,SATELIT
2,543,3.03167,43.36028,"03° 01' 54.00'' Est, 43° 21' 37.00'' Nord",34225,Chemin de Montfaucon,résidence de Mme SOUTADE,34620,PUISSERGUIER,23/05/2002,En extérieur,FicheMesure543.pdf,Oui,0.54,Divers,APAVE
3,545,3.03278,43.36167,"03° 01' 58.00'' Est, 43° 21' 42.00'' Nord",34225,Chemin de Quarante,résidence de M. GONZALEZ,34620,PUISSERGUIER,23/05/2002,En extérieur,FicheMesure545.pdf,Oui,0.20,Divers,APAVE
4,850,3.56444,43.64583,"03° 33' 52.00'' Est, 43° 38' 45.00'' Nord",34114,480 Chemin de Pioch Courbi,Chez Mme et M. GALOIS,34150,GIGNAC,10/10/2002,En extérieur,FicheMesure850.pdf,Oui,0.53,Rue / Route / Parking,APAVE

In [5]:
df.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [6]:
df=df.assign(target=1)
print(df)

     Numéro de mesure  Longitude  Latitude  \
0                 175    3.91611  43.58528
1                 180    4.04194  43.64694
2                 543    3.03167  43.36028
3                 545    3.03278  43.36167
4                 850    3.56444  43.64583
..                ...        ...       ...
907            159667    3.87667  43.59809
908            160107    3.86363  43.60516
909            160146    3.22983  43.36141
910            160274    3.86367  43.60505
911            160278    3.48046  43.28074

                                      Position  Insee  \
0    03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129
1    04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176
2    03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225
3    03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225
4    03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114
..                                         ...    ...
907  03° 52' 36.02'' Est, 43° 35' 53.11'' Nord  34172
908  03° 51' 49.05'' Est, 43° 36' 18.59'' Nord  34172
909  03° 13' 47.39'' Est, 43° 21' 41.09'' Nord  34032
910  03° 51' 49.20'' Est, 43° 36' 18.19'' Nord  34172
911  03° 28' 49.64'' Est, 43° 16' 50.65'' Nord  34003

                                 Adresse                 Complément  \
0                             Mas de Gau                        NaN
1    5539 Rue Lou Claou de la Oulivettas                        NaN
2                   Chemin de Montfaucon  résidence de  Mme SOUTADE
3                     Chemin de Quarante  résidence de  M. GONZALEZ
4             480 Chemin de Pioch Courbi      Chez Mme et M. GALOIS
..                                   ...                        ...
907                  25 Avenue de Maurin                        NaN
908                   47 Rue Lafeuillade                        NaN
909                    9 Rue des Terries                        NaN
910                   47 Rue Lafeuillade                        NaN
911            29 Chemin de la Roselière                        NaN

     Code postal       Commune Date de mesure Mesure réalisée  \
0          34970        LATTES     06/12/2001    En extérieur
1          34130      MUDAISON     06/12/2001    En extérieur
2          34620  PUISSERGUIER     23/05/2002    En extérieur
3          34620  PUISSERGUIER     23/05/2002    En extérieur
4          34150        GIGNAC     10/10/2002    En extérieur
..           ...           ...            ...             ...
907        34000   MONTPELLIER     05/08/2020    En extérieur
908        34070   MONTPELLIER     23/09/2020    En extérieur
909        34500       BEZIERS     30/09/2020    En extérieur
910        34070   MONTPELLIER     06/10/2020    En extérieur
911        34300          AGDE     06/10/2020    En extérieur

                 Rapport Conformité de la mesure  Niveau_global  \
0     FicheMesure175.pdf                     Oui           0.00
1     FicheMesure180.pdf                     Oui           0.00
2     FicheMesure543.pdf                     Oui           0.54
3     FicheMesure545.pdf                     Oui           0.20
4     FicheMesure850.pdf                     Oui           0.53
..                   ...                     ...            ...
907  R_SO9325_5_1PUB.pdf                     Oui           0.79
908  R_SO9400_2_3PUB.pdf                     Oui           0.67
909  R_SO9325_5_2PUB.pdf                     Oui           3.27
910  R_SO9412_2_2PUB.pdf                     Oui           0.92
911  R_SO9352_3_1PUB.pdf                     Oui           1.29

      Type d'environnement Laboratoire  target
0                   Divers     SATELIT       1
1                   Divers     SATELIT       1
2                   Divers       APAVE       1
3                   Divers       APAVE       1
4    Rue / Route / Parking       APAVE       1
..                     ...         ...     ...
907      Lieu d'habitation        EXEM       1
908      Lieu d'habitation        EXEM       1
909      Lieu d'habitation        EXEM       1
910      Lieu d'habitation        EXEM       1
911      Lieu d'habitation        EXEM       1

[912 rows x 17 columns]

In [7]:
df.columns

Index(['Numéro de mesure', 'Longitude', 'Latitude', 'Position', 'Insee',
       'Adresse', 'Complément', 'Code postal', 'Commune', 'Date de mesure',
       'Mesure réalisée', 'Rapport', 'Conformité de la mesure',
       'Niveau_global', 'Type d'environnement', 'Laboratoire', 'target'],
      dtype='object')

## `Fonction Target` :

In [8]:
def target():
    for t in range(0,len(df)):
        if df['Niveau_global'][t] > 6 :
            df['target'][t] = 0
            print(df['Niveau_global'][t])

In [9]:
target()

9.63
8.44
8.03
9.06
9.05
6.65
15.66
25.39
10.33
9.1
6.98
21.03
10.57
8.52

<ipython-input-8-e39c486678de>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target'][t] = 0

In [10]:
pd.crosstab(df.target, "freq")

col_0   freq
target
0         14
1        898

In [11]:
df.head()

,Numéro de mesure,Longitude,Latitude,Position,Insee,Adresse,Complément,Code postal,Commune,Date de mesure,Mesure réalisée,Rapport,Conformité de la mesure,Niveau_global,Type d'environnement,Laboratoire,target
0,175,3.91611,43.58528,"03° 54' 58.00'' Est, 43° 35' 07.00'' Nord",34129,Mas de Gau,NaN,34970,LATTES,06/12/2001,En extérieur,FicheMesure175.pdf,Oui,0.00,Divers,SATELIT,1
1,180,4.04194,43.64694,"04° 02' 31.00'' Est, 43° 38' 49.00'' Nord",34176,5539 Rue Lou Claou de la Oulivettas,NaN,34130,MUDAISON,06/12/2001,En extérieur,FicheMesure180.pdf,Oui,0.00,Divers,SATELIT,1
2,543,3.03167,43.36028,"03° 01' 54.00'' Est, 43° 21' 37.00'' Nord",34225,Chemin de Montfaucon,résidence de Mme SOUTADE,34620,PUISSERGUIER,23/05/2002,En extérieur,FicheMesure543.pdf,Oui,0.54,Divers,APAVE,1
3,545,3.03278,43.36167,"03° 01' 58.00'' Est, 43° 21' 42.00'' Nord",34225,Chemin de Quarante,résidence de M. GONZALEZ,34620,PUISSERGUIER,23/05/2002,En extérieur,FicheMesure545.pdf,Oui,0.20,Divers,APAVE,1
4,850,3.56444,43.64583,"03° 33' 52.00'' Est, 43° 38' 45.00'' Nord",34114,480 Chemin de Pioch Courbi,Chez Mme et M. GALOIS,34150,GIGNAC,10/10/2002,En extérieur,FicheMesure850.pdf,Oui,0.53,Rue / Route / Parking,APAVE,1

In [12]:
X=df[['Numéro de mesure','Niveau_global']].to_numpy()
print(X)
y=df['target'].to_numpy()
print(y)

[[1.75000e+02 0.00000e+00]
 [1.80000e+02 0.00000e+00]
 [5.43000e+02 5.40000e-01]
 ...
 [1.60146e+05 3.27000e+00]
 [1.60274e+05 9.20000e-01]
 [1.60278e+05 1.29000e+00]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [14]:
from sklearn.linear_model import LogisticRegression 
#Create a l.Reg Classifier
logreg1 = LogisticRegression()
#Train the model using the training sets
logreg1.fit(X_train, y_train)
y_pred=logreg1.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[  3   0]
 [  0 271]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00       271

    accuracy                           1.00       274
   macro avg       1.00      1.00      1.00       274
weighted avg       1.00      1.00      1.00       274

1.0

#   ` Test du modèle avec des nouvelles données `

In [16]:
df1=pd.read_csv('nouvelle.csv',delimiter=';')
df1.head()

,Numéro de mesure,Longitude,Latitude,Position,Insee,Adresse,Complément,Code postal,Commune,Date de mesure,Mesure réalisée,Rapport,Conformité de la mesure,Niveau global,Type d'environnement,Laboratoire
0,1,3.91611,43.58528,"03° 54' 58.00'' Est, 43° 35' 07.00'' Nord",34129,Mas de Gau,NaN,34970,LATTES,06/12/2001,NaN,FicheMesure175.pdf,Oui,4.01,Divers,SATELIT
1,2,4.04194,43.64694,"04° 02' 31.00'' Est, 43° 38' 49.00'' Nord",34176,5539 Rue Lou Claou de la Oulivettas,NaN,34130,MUDAISON,06/12/2001,NaN,FicheMesure180.pdf,Oui,20.10,Divers,SATELIT
2,3,3.03167,43.36028,"03° 01' 54.00'' Est, 43° 21' 37.00'' Nord",34225,Chemin de Montfaucon,résidence de Mme SOUTADE,34620,PUISSERGUIER,23/05/2002,NaN,FicheMesure543.pdf,Oui,3.90,Divers,APAVE
3,4,3.03278,43.36167,"03° 01' 58.00'' Est, 43° 21' 42.00'' Nord",34225,Chemin de Quarante,résidence de M. GONZALEZ,34620,PUISSERGUIER,23/05/2002,NaN,FicheMesure545.pdf,Oui,2.30,Divers,APAVE
4,5,3.56444,43.64583,"03° 33' 52.00'' Est, 43° 38' 45.00'' Nord",34114,480 Chemin de Pioch Courbi,Chez Mme et M. GALOIS,34150,GIGNAC,10/10/2002,NaN,FicheMesure850.pdf,Oui,5.90,Rue / Route / Parking,APAVE

In [17]:
df1.rename(columns={'Niveau global': 'Niveau_global'}, inplace=True)

In [18]:
df1=df1.assign(target1=1)
print(df1)

    Numéro de mesure  Longitude  Latitude  \
0                  1    3.91611  43.58528
1                  2    4.04194  43.64694
2                  3    3.03167  43.36028
3                  4    3.03278  43.36167
4                  5    3.56444  43.64583
5                  6    3.56306  43.64806
6                  7    3.56306  43.64694
7                  8    3.91611  43.58500
8                  9    3.91667  43.58667
9                 10    3.87806  43.60556
10                11    3.82389  43.63361
11                12    3.94556  43.57028
12                13    3.68583  43.40194
13                14    3.37167  43.50944
14                15    3.37889  43.50611
15                16    3.83944  43.61694
16                17    3.83944  43.61611
17                18    3.86361  43.59278
18                19    3.86500  43.59306
19                20    3.60750  43.42583
20                21    3.88083  43.61611
21                22    3.73889  43.79167
22                23    3.74028  43.79250
23                24    3.82778  43.61361

                                     Position  Insee  \
0   03° 54' 58.00'' Est, 43° 35' 07.00'' Nord  34129
1   04° 02' 31.00'' Est, 43° 38' 49.00'' Nord  34176
2   03° 01' 54.00'' Est, 43° 21' 37.00'' Nord  34225
3   03° 01' 58.00'' Est, 43° 21' 42.00'' Nord  34225
4   03° 33' 52.00'' Est, 43° 38' 45.00'' Nord  34114
5   03° 33' 47.00'' Est, 43° 38' 53.00'' Nord  34114
6   03° 33' 47.00'' Est, 43° 38' 49.00'' Nord  34114
7   03° 54' 58.00'' Est, 43° 35' 06.00'' Nord  34129
8   03° 55' 00.00'' Est, 43° 35' 12.00'' Nord  34129
9   03° 52' 41.00'' Est, 43° 36' 20.00'' Nord  34172
10  03° 49' 26.00'' Est, 43° 38' 01.00'' Nord  34172
11  03° 56' 44.00'' Est, 43° 34' 13.00'' Nord  34198
12  03° 41' 09.00'' Est, 43° 24' 07.00'' Nord  34301
13  03° 22' 18.00'' Est, 43° 30' 34.00'' Nord  34063
14  03° 22' 44.00'' Est, 43° 30' 22.00'' Nord  34063
15  03° 50' 22.00'' Est, 43° 37' 01.00'' Nord  34172
16  03° 50' 22.00'' Est, 43° 36' 58.00'' Nord  34172
17  03° 51' 49.00'' Est, 43° 35' 34.00'' Nord  34172
18  03° 51' 54.00'' Est, 43° 35' 35.00'' Nord  34172
19  03° 36' 27.00'' Est, 43° 25' 33.00'' Nord  34157
20  03° 52' 51.00'' Est, 43° 36' 58.00'' Nord  34172
21  03° 44' 20.00'' Est, 43° 47' 30.00'' Nord  34274
22  03° 44' 25.00'' Est, 43° 47' 33.00'' Nord  34274
23  03° 49' 40.00'' Est, 43° 36' 49.00'' Nord  34172

                                              Adresse  \
0                                          Mas de Gau
1                 5539 Rue Lou Claou de la Oulivettas
2                                Chemin de Montfaucon
3                                  Chemin de Quarante
4                          480 Chemin de Pioch Courbi
5                                        Vieux chemin
6                          401 Chemin de Pioch Courbi
7                         Château d'eau de Boirargues
8               Avenue de la Mer - Garage Tunning XXS
9                                       16 Rue Durand
10                                 Cour des Provinces
11                            10 Rue du Château d'Eau
12                                 Chemin Saint Clair
13                               Chemin de l'herbette
14                                     Route de Nizas
15                                     623 Rue d'Alco
16                                     623 Rue d'Alco
17                             Rue Jacqueline Maillan
18                                   Rue Louis Aragon
19                     4 Rue Pierre Auguste Massaloup
20                                        Rue Lakanal
21  Camping "le Pic Saint Loup", route du Pic Sain...
22  Campind "Pic Saint Loup", route du Pic Saint Loup
23                                Square Louis Carles

                                           Complément  Code postal  \
0                                                 NaN        34970
1                                                 NaN        34130
2                           résidence de  Mme SOUTADE        34620
3                           résidence de  M. GONZALEZ        34620
4                               Chez Mme et M. GALOIS        34150
5                            Chez Mme et M. HERMITTE.        34150
6                                 Chez Mme et M. EON.        34150
7                           Au pied du château d'eau.        34970
8   Au début du chemin donnant sur le château d'ea...        34970
9   Sur le trottoir devant l'entrée du centre de f...        34000
10  Entre les entrées de n° 23 et 205, au pied des...        34080
11  Maison des Arts, devant l'entrée principale, c...        34470
12  Sur le point de vue / terrasse du parking Sain...        34200
13              Devant le club house du stade de Caux        34720
14                                  Au pied du pylône        34720
15  Sur le parking de la résidence Cour des Ecoles...        34080
16  Entre le bâtiment 3 de la résidence Cour des E...        34080
17        Quartier Croix d'argent, devant les garages        34070
18  Devant l'entrée de l'association à l'enfance, ...        34070
19               3ème étage, sur la terrasse à gauche        34140
20  Sur le trottoir, devant l'entrée du collège ca...        34080
21  Sur le terrain de jeu, à côté de la terrasse d...        34380
22  Au croisement des deux chemins qui font le tou...        34380
23  Entre les deux bancs, devant l'école maternell...        34080

                    Commune Date de mesure  Mesure réalisée  \
0                    LATTES     06/12/2001              NaN
1                  MUDAISON     06/12/2001              NaN
2              PUISSERGUIER     23/05/2002              NaN
3              PUISSERGUIER     23/05/2002              NaN
4                    GIGNAC     10/10/2002              NaN
5                    GIGNAC     10/10/2002              NaN
6                    GIGNAC     10/10/2002              NaN
7                    LATTES     22/01/2003              NaN
8                    LATTES     22/01/2003              NaN
9               MONTPELLIER     16/08/2006              NaN
10              MONTPELLIER     05/10/2006              NaN
11                   PEROLS     05/10/2006              NaN
12                     SETE     30/11/2006              NaN
13                     CAUX     20/12/2006              NaN
14                     CAUX     20/12/2006              NaN
15              MONTPELLIER     04/12/2006              NaN
16              MONTPELLIER     04/12/2006              NaN
17              MONTPELLIER     04/12/2006              NaN
18              MONTPELLIER     04/12/2006              NaN
19                     MEZE     09/01/2007              NaN
20              MONTPELLIER     07/03/2007              NaN
21  SAINT-MARTIN-DE-LONDRES     08/03/2007              NaN
22  SAINT-MARTIN-DE-LONDRES     08/03/2007              NaN
23              MONTPELLIER     18/04/2007              NaN

                 Rapport Conformité de la mesure  Niveau_global  \
0     FicheMesure175.pdf                     Oui           4.01
1     FicheMesure180.pdf                     Oui          20.10
2     FicheMesure543.pdf                     Oui           3.90
3     FicheMesure545.pdf                     Oui           2.30
4     FicheMesure850.pdf                     Oui           5.90
5     FicheMesure851.pdf                     Oui          10.02
6     FicheMesure852.pdf                     Oui           6.50
7    FicheMesure1072.pdf                     Oui           7.10
8    FicheMesure1073.pdf                     Oui           4.06
9    FicheMesure9169.pdf                     Oui           6.20
10   FicheMesure9524.pdf                     Oui           6.90
11   FicheMesure9529.pdf                     Oui           5.50
12   FicheMesure9907.pdf                     Oui           5.60
13  FicheMesure10048.pdf                     Oui           6.70
14  FicheMesure10050.pdf                     Oui          25.00
15  FicheMesure10061.pdf                     Oui           7.02
16  FicheMesure10062.pdf                     Oui           9.20
17  FicheMesure10063.pdf                     Oui           3.90
18  FicheMesure10064.pdf                     Oui          10.70
19  FicheMesure10148.pdf                     Oui           2.90
20  FicheMesure10669.pdf                     Oui           6.10
21  FicheMesure10675.pdf                     Oui           5.70
22  FicheMesure10676.pdf                     Oui           4.60
23  FicheMesure11186.pdf                     Oui           5.50

     Type d'environnement                  Laboratoire  target1
0                  Divers                      SATELIT        1
1                  Divers                      SATELIT        1
2                  Divers                        APAVE        1
3                  Divers                        APAVE        1
4   Rue / Route / Parking                        APAVE        1
5   Rue / Route / Parking                        APAVE        1
6   Rue / Route / Parking                        APAVE        1
7   Rue / Route / Parking  CSTB - Saint Martin d'Heres        1
8   Rue / Route / Parking                          NaN        1
9                     NaN                          NaN        1
10                    NaN                          NaN        1
11                    NaN                          NaN        1
12                    NaN                          NaN        1
13                    NaN                          NaN        1
14                    NaN                          NaN        1
15                    NaN                          NaN        1
16                    NaN                          NaN        1
17                    NaN  CSTB - Saint Martin d'Heres        1
18                    NaN                          NaN        1
19                    NaN                          NaN        1
20                    NaN                          NaN        1
21                    NaN                          NaN        1
22                    NaN                          NaN        1
23                    NaN                          NaN        1

## `Fonction Target1` :

In [19]:
def target1():
    for t in range(0,len(df1)):
        if df1['Niveau_global'][t] > 6 :
            df1['target1'][t] = 0
            print(df1['Niveau_global'][t])

In [20]:
target1()

20.1
10.02
6.5
7.1
6.2
6.9
6.7
25.0
7.02
9.2
10.7
6.1

<ipython-input-19-bbd9274d20b9>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['target1'][t] = 0

In [21]:
z=df1[['Numéro de mesure','Niveau_global']].to_numpy()
print(z)
a=df1['target1'].to_numpy()
print(a)

[[ 1.    4.01]
 [ 2.   20.1 ]
 [ 3.    3.9 ]
 [ 4.    2.3 ]
 [ 5.    5.9 ]
 [ 6.   10.02]
 [ 7.    6.5 ]
 [ 8.    7.1 ]
 [ 9.    4.06]
 [10.    6.2 ]
 [11.    6.9 ]
 [12.    5.5 ]
 [13.    5.6 ]
 [14.    6.7 ]
 [15.   25.  ]
 [16.    7.02]
 [17.    9.2 ]
 [18.    3.9 ]
 [19.   10.7 ]
 [20.    2.9 ]
 [21.    6.1 ]
 [22.    5.7 ]
 [23.    4.6 ]
 [24.    5.5 ]]
[1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 1 0 1 1 1]

In [22]:
y1_pred=logreg1.predict(z)
print(y1_pred)

[1 0 1 1 1 0 1 0 1 1 0 1 1 0 0 0 0 1 0 1 1 1 1 1]

In [23]:
pd.crosstab(df1.target1, "freq")

col_0    freq
target1
0          12
1          12

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [25]:
from sklearn.linear_model import LogisticRegression 
#Create a l.Reg Classifier
logreg1 = LogisticRegression()
#Train the model using the training sets
logreg1.fit(X_train, y_train)
y_pred=logreg1.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(a,y1_pred))
print(classification_report(a,y1_pred))
print(accuracy_score(a,y1_pred))

[[ 9  3]
 [ 0 12]]
              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.80      1.00      0.89        12

    accuracy                           0.88        24
   macro avg       0.90      0.88      0.87        24
weighted avg       0.90      0.88      0.87        24

0.875